Resources:
  
  MySecretB:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: Mysecret
      Description: This secret has a hardcoded password in SecretString (use GenerateSecretString instead)
      SecretString: !Sub 
        - '{"username": "${username}", "password": "${password}"}'
        - username: !ImportValue RDSUsername
          password: !ImportValue RDSPassword


  SecretRDSInstanceAttachment:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      SecretId: !Ref MySecretB
      TargetId: 
        Fn::ImportValue: MyRDS
      TargetType: AWS::RDS::DBInstance

Outputs:
  secret:
    Value: !Ref MySecretB
    Description: Secret ID
    Export:
      Name: "MySecretid"


